version: '3.3'
services:
  Node0:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-0","--validator"]
    networks: 
      - one
  Node1:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-1"]
    networks: 
      - one
  Node2:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-2"]
    networks: 
      - two
  Node3:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-3","--validator"]
    networks: 
      - two
      - one
  Node4:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-4"]
    networks: 
      - two
networks:
  one:
    driver: bridge
    internal: false
  two:
    driver : bridge
    internal: false
