version: '3.3'
services:
  Node0:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-0","--validator"]
    networks: 
      - one
  Node1:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-1"]
    networks: 
      - one
  Node2:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-2"]
    networks: 
      - two
  Node3:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-3"]
    networks: 
      - two
  Node4:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-4","--validator","/var/tmp/public_addresses.txt"]
    #command: ["Node-4"]
    networks: 
      - one
      - two
networks:
  one:
    external: True 
  two:
    external: True 

