version: '3.3'
services:
  Node0:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-0","--validator", "/ip4/172.21.1.0/tcp/4000"]
    networks: 
      - main
  Node1:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-1"]
    networks: 
      - main
  Node2:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-2", "--node-key 64d6a1c09ea28d9e863d1cfe52e5d11fdcca4716febf0e5071299367b8eb15ac", "/ip4/172.21.1.2/tcp/4000"]
    networks: 
      - side
  Node3:
    image: node
    volumes:
      - ~/logs:/var/tmp/
    command: ["Node-3", " ", "/ip4/172.21.1.3/tcp/4000", "/ip4/172.21.1.2/tcp/4000/p2p/12D3KooWS5Z1PDPFVtNdAurtNxvHujpR8DRzbsbdgUofRP6B54SN"]
    networks: 
      - side
      - main
networks: 
  main: 
    driver: bridge
    internal: false
  side: 
    driver: bridge
    internal: false